version: '3'

services:
  admin.dev:
    tty: true
    build:
      context: ../admin-manager
      dockerfile: Dev.Dockerfile
    volumes:
      - ../admin-manager/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      HOST: '0.0.0.0'
      PORT: '3001'
    ports:
      - '3001:3001'
    entrypoint: ./scripts/development.sh

  client.dev:
    tty: true
    build:
      context: ../client-manager
      dockerfile: Dev.Dockerfile
    volumes:
      - ../client-manager/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      HOST: '0.0.0.0'
      PORT: '3002'
    ports:
      - '3002:3002'
    entrypoint: ./scripts/development.sh
