version: '3'

services:
  admin.dev:
    tty: true
    build:
      context: ../admin-manager
      dockerfile: Dev.Dockerfile
    volumes:
      - ../admin-manager/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '3001:3001'
    command: './node_modules/.bin/nuxt-ts -H 0.0.0.0 -p 3001'

  client.dev:
    tty: true
    build:
      context: ../client-manager
      dockerfile: Dev.Dockerfile
    volumes:
      - ../client-manager/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '3002:3002'
    command: './node_modules/.bin/nuxt-ts -H 0.0.0.0 -p 3002'
